export enum VotesActionTypes {
  ADD_VOTE = "ADD_VOTE",
  DELETE_VOTE = "DELETE_VOTE",
  EDIT_VOTE = "EDIT_VOTE",
  ERROR_VOTE = "ERROR_VOTE",
  GET_VOTES = "GET_VOTES",
  INCREMENT_VOTE = "INCREMENT_VOTE",
  LOAD_VOTES = "LOAD_VOTES",
}
